### ISSUE TITLE
Homepage Edits:

### ISSUE THREAD

**Issue by kreativekommit** [kreativekommit/shark-tank-marketing#4]
the title:
 " Shark Tank  - your key to exploring Web 3.0"
 change to:
  " Shark Tank NFT -Tech Pass- your key to Web 3 "
 
 Replace the text with the following:
<  
  Join the frenzy, and explore the possibilities.  We are on a mission to develop a unique Web3 development brand together with our community and our shared passion for NFTs and gaming!   Soon to be released a Community Vs Community fun battle game, and more!
  
  The initial sale of the Shark Tank Tech Pass will be announced soon. Check back soon for the Release Date.
  >
  
  Please edit the current opensea button to ONLY say:
  
"  Release Date Coming Soon"
  
Rather than it being a opensea link, we will change this into a countdown timer later once we know when we will launch the nfts.

**Comment by moussa32** [comment]
Issue has been resolved
