### ISSUE TITLE
Footer:

### ISSUE THREAD

**Issue by kreativekommit** [kreativekommit/shark-tank-marketing#6]
Only have the following text links on the footer: (we will provide links later)

[Purchase]
[Blog]
[Privacy Policy
[Terms of Sale]
[Smart Contract] (TBA)

Lower right of the footer: 

Verified Smart Contract: [View on Etherscan](https://)
Contact us at [admin@sharktank.media](mailto:admin@sharktank.media)

**Comment by moussa32** [comment]
Issue has been resolved
